### ISSUE TITLE
Comparison of selected text with clipboard text does not work.

### ISSUE THREAD

**Issue by Ishtef** [paulber19/notepadPlusPlusAccessEnhancementNVDAAddon#1]
NVDA version 2023.1,
Notepad++version 8.54,
Windows 11 version 22H2.

Nothing happens when I press ctrl+windows+f2.
There is a selected text in the editor. There is also text in the buffer.
When running the script, there is no reaction at all, as if it is not there.

**Comment by paulber19** [comment]
Thank you very much for reporting this error.
This will be fixed in the next version.
