### ISSUE TITLE
Inaccuracies in the documentation regarding input gestures.

### ISSUE THREAD

**Issue by Ishtef** [paulber19/notepadPlusPlusAccessEnhancementNVDAAddon#2]
There is an error in point 3.3.1 of the manual (Notification of lines that are too long).
The command windows+control+F4 is indicated in the second point of ways to enable or disable this function.
However, in input gestures, this command is intended for the script to activate the dialog for converting markdown and txt2tags files to html. And for switching the function of signaling about long lines, there is no corresponding item in the "Input Gestures" dialog.

It is also written in point 5.1 that to activate the markdown to html conversion dialog, you need to use the "KEY Compil" command.
But there is no "KEY Compil" command in the addon keys.t2tconf file.

**Comment by paulber19** [comment]
Thank you very much for reporting this error.
This will be fixed in the next version.
Best regards.
